networks:
  noteflix-net:
    external: true

volumes:
  noteflix-data:
    name: noteflix-data
    external: true
  ollama:
    name: ollama
    external: true

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    networks: [noteflix-net]
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped

  api:
    image: noteflix-api:v3
    build: .
    container_name: noteflix
    networks: [noteflix-net]
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    volumes:
      - noteflix-data:/data
    env_file:
      - .env
    environment:
      - DATA_ROOT=/data
      - OLLAMA_BASE=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3}
      - PIPER_VOICE_A=/app/models/en_US-amy-medium.onnx
      - PIPER_VOICE_B=/app/models/en_US-ryan-high.onnx
    restart: unless-stopped
